CREATE OR REPLACE SYNONYM DIM_DATE FOR SABDADM.DIM_DATE;
CREATE OR REPLACE SYNONYM DIM_CURRENCY FOR SABDADM.DIM_CURRENCY;
CREATE OR REPLACE SYNONYM DIM_COUNTRY FOR SABDADM.DIM_COUNTRY;
CREATE OR REPLACE SYNONYM DIM_CUST_GROUP FOR SABDADM.DIM_CUST_GROUP;
CREATE OR REPLACE SYNONYM DIM_CUSTOMER FOR SABDADM.DIM_CUSTOMER;
CREATE OR REPLACE SYNONYM DIM_ACCOUNT FOR SABDADM.DIM_ACCOUNT;
CREATE OR REPLACE SYNONYM DIM_OPERATION FOR SABDADM.DIM_OPERATION;
CREATE OR REPLACE SYNONYM DIM_COMMISSION FOR SABDADM.DIM_COMMISSION;