GRANT SELECT ON DIM_DATE TO SABDUSER;
GRANT SELECT ON DIM_CURRENCY TO SABDUSER;
GRANT SELECT ON DIM_COUNTRY TO SABDUSER;
GRANT SELECT ON DIM_CUST_GROUP TO SABDUSER;
GRANT SELECT ON DIM_CUSTOMER TO SABDUSER;
GRANT SELECT ON DIM_ACCOUNT TO SABDUSER;
GRANT SELECT ON DIM_OPERATION TO SABDUSER;
GRANT SELECT ON DIM_COMMISSION TO SABDUSER;

