CREATE OR REPLACE TYPE err_data_ob AS OBJECT(

    PROCESS_NAME VARCHAR2(255 CHAR),
    ERROR_CODE VARCHAR2(10 CHAR),
    ERROR_MESSAGE VARCHAR2(255 CHAR),
    ROW_IDENTIFIER VARCHAR2(255 CHAR)
);
/

CREATE OR REPLACE TYPE err_data_nt IS TABLE OF err_data_ob;
/